// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GenerateFromTemplateHandlerFunc turns a function with the right signature into a generate from template handler
type GenerateFromTemplateHandlerFunc func(GenerateFromTemplateParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GenerateFromTemplateHandlerFunc) Handle(params GenerateFromTemplateParams) middleware.Responder {
	return fn(params)
}

// GenerateFromTemplateHandler interface for that can handle valid generate from template params
type GenerateFromTemplateHandler interface {
	Handle(GenerateFromTemplateParams) middleware.Responder
}

// NewGenerateFromTemplate creates a new http.Handler for the generate from template operation
func NewGenerateFromTemplate(ctx *middleware.Context, handler GenerateFromTemplateHandler) *GenerateFromTemplate {
	return &GenerateFromTemplate{Context: ctx, Handler: handler}
}

/*GenerateFromTemplate swagger:route POST /generateFromTemplate generateFromTemplate

Generate archive from template

*/
type GenerateFromTemplate struct {
	Context *middleware.Context
	Handler GenerateFromTemplateHandler
}

func (o *GenerateFromTemplate) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGenerateFromTemplateParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
