// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/kathra-project/kathra-codegen-helm/models"
)

// GetTemplatesOKCode is the HTTP code returned for type GetTemplatesOK
const GetTemplatesOKCode int = 200

/*GetTemplatesOK Get all CodeGenTemplate

swagger:response getTemplatesOK
*/
type GetTemplatesOK struct {

	/*
	  In: Body
	*/
	Payload []*models.CodeGenTemplate `json:"body,omitempty"`
}

// NewGetTemplatesOK creates GetTemplatesOK with default headers values
func NewGetTemplatesOK() *GetTemplatesOK {

	return &GetTemplatesOK{}
}

// WithPayload adds the payload to the get templates o k response
func (o *GetTemplatesOK) WithPayload(payload []*models.CodeGenTemplate) *GetTemplatesOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get templates o k response
func (o *GetTemplatesOK) SetPayload(payload []*models.CodeGenTemplate) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetTemplatesOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.CodeGenTemplate, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
