// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi Kathra CodeGenerator Manager
KATHRA CodeGenerator API permetting generate sources


    Schemes:
      http
    Host: localhost
    BasePath: /api/v1
    Version: 1.1.0-SNAPSHOT

    Consumes:
    - application/json

    Produces:
    - application/json
    - application/octet-stream

swagger:meta
*/
package restapi
