// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// CodeGenTemplateArgument code gen template argument
// swagger:model CodeGenTemplateArgument
type CodeGenTemplateArgument struct {

	// Argument constraint
	Contrainst string `json:"contrainst,omitempty"`

	// Argument key to generate codegen
	Key string `json:"key,omitempty"`

	// Argument value to generate codegen
	Value string `json:"value,omitempty"`
}

// Validate validates this code gen template argument
func (m *CodeGenTemplateArgument) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CodeGenTemplateArgument) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CodeGenTemplateArgument) UnmarshalBinary(b []byte) error {
	var res CodeGenTemplateArgument
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
